[package]
name = "wasmos"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmos-macro = "0.0.1"
tokio = { version = "1", features = ["rt"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
